# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ChristopheDebruyne.be
email: c.debruyne[-at-]uliege.be
description: >- # this means to ignore newlines until "baseurl:"
  Computer scientist, geek, city boy, shower pop star, and cat lover! (he/him) ğŸ³ï¸â€ğŸŒˆğŸˆğŸŸğŸ§™â€â™‚ï¸
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: chrdebru
#github_username:  chrdebru
#google_scholar_username: nx2KW_IAAAAJ
copyright: Â©ï¸ 2025 

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-remote-theme

# set up remote_theme
remote_theme: jekyll/minima

# Build settings
minima:
  social_links:
    - { icon: github,         url: "https://github.com/chrdebru" }
    - { icon: google-scholar,  url: "https://scholar.google.com/citations?user=nx2KW_IAAAAJ" }
    - { icon: linkedin,       url: "https://www.linkedin.com/in/christophedebruyne" }
    - { icon: bluesky,        url: "https://bsky.app/profile/chrdebru.bsky.social" }
    - { icon: youtube,        url: "https://www.youtube.com/@chrdebru" }

header_pages:
  - index.md
  - publications.md
  - outreach.md
  - group.md
  - teaching.md
  - thesistopics.md
  - blog.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - ontologies/
  - toxin/
  - cats/
  - IRL/
  - 404.md
  - courses/
  - cats.html
